# ==================================================================
# CGI SHOWCASE CONFIGURATION FOR WEBSERV
# ==================================================================

# Configuration for the CGI showcase server running on localhost:3000
# This configuration serves static HTML/PHP files, handles CGI scripts,
# and supports file uploads with proper error handling.

server {
    listen 3002;
    server_name localhost;

	allowed_methods GET POST DELETE;
    root /home/malee/42_Projects/webserv/www/html;
    index index.php index.html;
    autoindex on;
	cgi_path true;

    client_max_body_size 10M;
    status_page 400 /error/400.html;
    status_page 403 /error/403.html;
    status_page 404 /error/404.html;
    status_page 500 /error/500.html;

    location /upload/ {
        allowed_methods GET POST DELETE;

        root /home/malee/42_Projects/webserv/www/html;
        cgi_path true;
        upload_path /home/malee/42_Projects/webserv/www/html/uploads;
    }
}
