server {
	listen localhost:8080;
	server_name localhost;

	root /home/malee/42_Projects/webserv/ww1;

	location / {
		allowed_methods GET;
		autoindex on;
	}

	location /put_test/ {
		allowed_methods PUT;
		upload_path /home/malee/42_Projects/webserv/ww1/uploads;
	}

	location /post_body/ {
		allowed_methods POST;
		client_max_body_size 1K;
	}

	location /directory/ {
		allowed_methods GET POST;
		root /home/malee/42_Projects/webserv/ww1/YoupiBanane;
		index youpi.bad_extension;
		autoindex on;
	}

	location /directory/nop {
		allowed_methods GET;
		root /home/malee/42_Projects/webserv/ww1/YoupiBanane;
		index youpi.bad_extension;
		autoindex on;
	}
}

